[fabric-api]
src.webpage = "https://api.modrinth.com/v2/project/fabric-api/version"
src.regex = "fabric-api-([0-9]+\\.[0-9]+\\.[0-9]+\\+[0-9]+\\.[0-9]+)\\.jar"
fetch.url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/lVXlbH4w/fabric-api-$ver.jar"
url.name = "fabric-api.jar"

[auth-fabric]
src.webpage = "https://api.modrinth.com/v2/project/auth/version"
src.regex = "auth-(v[0-9]+\\.[0-9]+\\.[0-9]+)\\.jar"
fetch.url = "https://cdn.modrinth.com/data/RpXNx59A/versions/363AFEd4/auth-$ver.jar"
url.name = "auth.jar"

[ps4-pkg-tools]
src.github = "xXJSONDeruloXx/ps4-pkg-tools"
fetch.github = "xXJSONDeruloXx/ps4-pkg-tools"
git.fetchSubmodules = true

[voicechat]
src.webpage = "https://api.modrinth.com/v2/project/simple-voice-chat/version"
src.regex = "voicechat-fabric-([0-9]+\\.[0-9]+\\.[0-9]+\\+[0-9]+\\.[0-9]+)\\.jar"
fetch.url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/3SOh5iiX/voicechat-fabric-$ver.jar"
url.name = "voicechat-fabric.jar"

