[fabric-api]
src.webpage = "https://api.modrinth.com/v2/project/fabric-api/version"
src.regex = "fabric-api-([0-9]+\\.[0-9]+\\.[0-9]+\\+26\\.2)\\.jar"
fetch.url = "https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api/$ver/fabric-api-$ver.jar"
url.name = "fabric-api.jar"

[easyauth]
src.github_tag = "NikitaCartes/EasyAuth"
fetch.url = "https://github.com/NikitaCartes/EasyAuth/releases/download/$ver/easyauth-mc26.2-$ver.jar"
url.name = "easyauth.jar"

[skinsrestorer]
src.github = "SkinsRestorer/SkinsRestorer"
fetch.url = "https://github.com/SkinsRestorer/SkinsRestorer/releases/download/$ver/SkinsRestorer-Mod-Fabric-$ver.jar"
url.name = "skinsrestorer.jar"
