return {
	{ import = "thiago.plugins.blink_cmp" },
	{ import = "thiago.plugins.lsp" },
	{ import = "thiago.plugins.conform" },
	{ import = "thiago.plugins.harpoon" },
	{ import = "thiago.plugins.lazygit" },
	{ import = "thiago.plugins.nvim_lint" },
	{ import = "thiago.plugins.markdown" },
	{ import = "thiago.plugins.oil" },
	{ import = "thiago.plugins.snacks" },
	{ import = "thiago.plugins.snippets" },
	{ import = "thiago.plugins.telescope" },
	{ import = "thiago.plugins.treesitter" },
	{ import = "thiago.plugins.vimtex" },
	{ import = "thiago.plugins.mini" },
	{
		"plenary.nvim",
		dep_of = { "harpoon2", "lazygit.nvim", "telescope.nvim" },
	},
	{ "nvim-web-devicons", dep_of = { "oil.nvim", "render-markdown.nvim" } },
	{
		"rose-pine",
		colorscheme = "rose-pine",
	},
}
