# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  easyauth = {
    pname = "easyauth";
    version = "3.4.3-SNAPSHOT.49";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/aZj58GfX/versions/brHsihQ7/easyauth-mc26.2-3.4.3-SNAPSHOT.49.jar";
      name = "easyauth.jar";
      sha256 = "sha256-ZJ6yhQ8bXHaWJ1Q31ZWQFplfkx3MAPSCKpSXyCKjOo8=";
    };
  };
  fabric-api = {
    pname = "fabric-api";
    version = "0.155.2+26.2";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/lVXlbH4w/fabric-api-0.155.2+26.2.jar";
      name = "fabric-api.jar";
      sha256 = "sha256-1lGMdwAky+ilViSPFvzbuRxqYvUCJ6bDuugZBRHiwbg=";
    };
  };
  ps4-pkg-tools = {
    pname = "ps4-pkg-tools";
    version = "v20250825-123142-e7c40358";
    src = fetchFromGitHub {
      owner = "xXJSONDeruloXx";
      repo = "ps4-pkg-tools";
      rev = "v20250825-123142-e7c40358";
      fetchSubmodules = true;
      sha256 = "sha256-t4vs2OEAssSY28XwQngNGv8wui1VKjlYLDpj3JZL/Fg=";
    };
  };
  skinsrestorer = {
    pname = "skinsrestorer";
    version = "15.12.5";
    src = fetchurl {
      url = "https://cdn.modrinth.com/data/TsLS8Py5/versions/wGTF2aVu/SkinsRestorer-Mod-Fabric-15.12.5.jar";
      name = "skinsrestorer.jar";
      sha256 = "sha256-Vp2CXFPKdKf79CnjnIswiNfhIa/tCUpTZeUaDMgChRk=";
    };
  };
}
