# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  authme = {
    pname = "authme";
    version = "5.6.0";
    src = fetchurl {
      url = "https://github.com/AuthMe/AuthMeReloaded/releases/download/5.6.0/AuthMe-5.6.0.jar";
      name = "AuthMe.jar";
      sha256 = "sha256-gDcbqACHwU5J+tkIxYHqdneUPbS5aHYMBT07sNJnZNE=";
    };
  };
  floodgate-spigot = {
    pname = "floodgate-spigot";
    version = "latest";
    src = fetchurl {
      url = "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot";
      name = "Floodgate-Spigot.jar";
      sha256 = "sha256-1kevbNh1zsZbJj/+TlEgTabptu24tIHTe6/czILxBdk=";
    };
  };
  floodgate-sqlite-database = {
    pname = "floodgate-sqlite-database";
    version = "latest";
    src = fetchurl {
      url = "https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/fix-weird-via-issue/lastSuccessfulBuild/artifact/database/sqlite/build/libs/floodgate-sqlite-database.jar";
      name = "floodgate-sqlite-database.jar";
      sha256 = "sha256-30rpHkUvcSTxG5fWJTV7ALEyCMBW5oxUc+FZmx5EMxc=";
    };
  };
  geyser-spigot = {
    pname = "geyser-spigot";
    version = "latest";
    src = fetchurl {
      url = "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot";
      name = "Geyser-Spigot.jar";
      sha256 = "sha256-oCAVw5Dz4OKt9vb42Kbhw0ZIL7XAQ0exPNNvEpoKBDA=";
    };
  };
  ps4-pkg-tools = {
    pname = "ps4-pkg-tools";
    version = "v20250825-123142-e7c40358";
    src = fetchFromGitHub {
      owner = "xXJSONDeruloXx";
      repo = "ps4-pkg-tools";
      rev = "v20250825-123142-e7c40358";
      fetchSubmodules = true;
      sha256 = "sha256-t4vs2OEAssSY28XwQngNGv8wui1VKjlYLDpj3JZL/Fg=";
    };
  };
  skinsrestorer = {
    pname = "skinsrestorer";
    version = "15.10.0";
    src = fetchurl {
      url = "https://github.com/SkinsRestorer/SkinsRestorer/releases/download/15.10.0/SkinsRestorer.jar";
      name = "SkinsRestorer.jar";
      sha256 = "sha256-FY5s+nLwZqsfHp/MiBE5o2gQv1mTw/4b1HuyjoADtZY=";
    };
  };
  viaversion = {
    pname = "viaversion";
    version = "5.7.1";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaVersion/releases/download/5.7.1/ViaVersion-5.7.1.jar";
      name = "ViaVersion.jar";
      sha256 = "sha256-e5s9WjhExO5bGJZjJ2ku5+aY5311a4sPt4XlOg+apKU=";
    };
  };
}
