# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  easyauth = {
    pname = "easyauth";
    version = "3.4.4";
    src = fetchurl {
      url = "https://github.com/NikitaCartes/EasyAuth/releases/download/3.4.4/easyauth-mc26.2-3.4.4.jar";
      name = "easyauth.jar";
      sha256 = "sha256-GUXDf5imDfWqM8GCYUE7UjqpSVhaDj17hw08+gLmT2I=";
    };
  };
  fabric-api = {
    pname = "fabric-api";
    version = "0.157.0+26.2";
    src = fetchurl {
      url = "https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api/0.157.0+26.2/fabric-api-0.157.0+26.2.jar";
      name = "fabric-api.jar";
      sha256 = "sha256-rLfckKBDBRnElUgHTT+/b9gdEwY/CPCvNEsqawikJiA=";
    };
  };
  skinsrestorer = {
    pname = "skinsrestorer";
    version = "15.12.5";
    src = fetchurl {
      url = "https://github.com/SkinsRestorer/SkinsRestorer/releases/download/15.12.5/SkinsRestorer-Mod-Fabric-15.12.5.jar";
      name = "skinsrestorer.jar";
      sha256 = "sha256-Vp2CXFPKdKf79CnjnIswiNfhIa/tCUpTZeUaDMgChRk=";
    };
  };
}
