keys:
  - &adminthi age1xne7lez8hrgtq00etfl3d8rf89qttsujm9zq4dpxulc3eeljw5hst73w05
  - &hosthome age1q36w5awq5ds3ncx7q5hsutt3xtshs8c7x8wxtx74fcfwssqahe3qev8mk8
  - &hosthomeserver age1pftkspe3h0elx3hd8000qtx89s6qf6s7l0mgk9k6thxg0fnc432s58ynqq

creation_rules:
  - path_regex: store/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *adminthi
          - *hosthome
          - *hosthomeserver
