keys:
  - &adminthi age1e74zg4ddpzeje62ngld2fuwc5amtk9udlzw3jzgl0ejdey963cuqty8xr3

creation_rules:
  - path_regex: store/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *adminthi
