keys:
  - &adminthi age1e74zg4ddpzeje62ngld2fuwc5amtk9udlzw3jzgl0ejdey963cuqty8xr3

  - &homeserverthiago age1qqe83u6k3ftzlng38juaqgkn84s8tghh9vn6qa98fdpnpwjgfqsq22aqvu
  - &homeserver age1pftkspe3h0elx3hd8000qtx89s6qf6s7l0mgk9k6thxg0fnc432s58ynqq

creation_rules:
  - path_regex: store/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *adminthi
          - *homeserver
          - *homeserverthiago
