keys:
  - &thiago_home age1e74zg4ddpzeje62ngld2fuwc5amtk9udlzw3jzgl0ejdey963cuqty8xr3
  - &home_host age1q36w5awq5ds3ncx7q5hsutt3xtshs8c7x8wxtx74fcfwssqahe3qev8mk8
  - &homeserver_host age1pftkspe3h0elx3hd8000qtx89s6qf6s7l0mgk9k6thxg0fnc432s58ynqq

creation_rules:
  - path_regex: store/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *thiago_home
          - *home_host
          - *homeserver_host
