{
  imports = [
    ./secure_boot.nix
    ./nix_setup.nix
    ./user_preferences.nix
    ./shared_folders.nix
    ./steam_shared.nix
    ./features/gaming/default.nix
    ./features/graphics/default.nix
    ./features/audio/default.nix
    ./features/virtualization/default.nix
    ./features/desktop/display-manager.nix
    ./features/desktop/hyprland.nix
    ./features/desktop/stylix.nix
    ./features/services/bluetooth.nix
    ./features/services/printing.nix
    ./features/services/openrgb.nix
    ./features/services/playit.nix
    ./features/services/gnome-keyring.nix
    ./features/services/thunar.nix
    ./features/networking/default.nix
    ./features/boot/default.nix
    ./features/hardware/amdgpu.nix
    ./features/hardware/keyboard.nix
  ];
}
